### ISSUE TITLE
儿童中心》公告信息管理

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#10]
http://babyplan.bjfpa.org.cn/staff/announcements
时间格式奇怪，时间也不对
![image](https://cloud.githubusercontent.com/assets/23470504/20298255/c93f5000-ab4f-11e6-8c46-bf6538047713.png)

提示文字不对
![image](https://cloud.githubusercontent.com/assets/23470504/20298363/7fd95de2-ab50-11e6-8125-1bdc747b62ad.png)

**Comment by JesseYang** [comment]
已修改
