### ISSUE TITLE
工作人员微信端》绘本借阅》绘本查询

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#104]
使用账号13511111111   111111
绘本在PC端是下架的，但是查询时现实的状态是“在架上”
另：下载的二维码，不管格式如何，能不能命名用绘本名字啊？我这边才下了2、3个尚且分不清，就更不用说正常使用的工作人员了。而且导出比如说一页A4大小能放4个或6个二维码word或者pdf感觉比导出压缩包强啊……
![5833b008f6e1d53a08dbc5ea](https://cloud.githubusercontent.com/assets/23470504/20509065/fdde35fa-b0a0-11e6-996b-18f1ad82cd86.png)

**Comment by JesseYang** [comment]
状态现实错误已修改；下载的二维码压缩包已改成用绘本名称命名；导出成pdf很麻烦，回头再改
