### ISSUE TITLE
儿童中心》公告信息管理》公告

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#11]
http://babyplan.bjfpa.org.cn/staff/announcements?profile=local
公告的封面图在列表页显示为文章第一张图，纯文字公告则无图。
新建公告页有封面配图项上传不上去。

在列表页，状态：未公布 好像是写死的。

另：公告只有点击“详情”才能进入公告详情页面，理论上来说点击公告标题和配图应该也能进去比较好？我已经操作了很多次点标题没反应才意识到要点“详情”。

**Comment by JesseYang** [comment]
已修改
