### ISSUE TITLE
管理员后台》注册

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#13]
上为360浏览器，下为chrome浏览器效果
![image](https://cloud.githubusercontent.com/assets/23470504/20299716/0c36fd8e-ab57-11e6-971d-5c889c741b17.png)
![image](https://cloud.githubusercontent.com/assets/23470504/20299779/4aac6e78-ab57-11e6-8a45-30863aeacdd6.png)
感觉是登录那边记住账号密码的那两个，莫名对应到了这边的验证码和新密码造成的后果吧……

**Comment by JesseYang** [comment]
这是浏览器缓存导致的
