### ISSUE TITLE
儿童中心》公告信息管理

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#14]
建议儿童中心和管理员后台公告页用字统一一下，把儿童中心的详细内容的字号也改成12号（目测）吧
![image](https://cloud.githubusercontent.com/assets/23470504/20300149/bf3a24c8-ab58-11e6-8ce1-ded6cf425b4d.png)
![image](https://cloud.githubusercontent.com/assets/23470504/20300162/caf51af2-ab58-11e6-9723-4805a6216390.png)

**Comment by Alanbuddy** [comment]
@WenJunwen 已修改
