### ISSUE TITLE
儿童中心》绘本管理》绘本详情》编辑

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#19]
http://babyplan.bjfpa.org.cn/staff/books/57df5c4c98a9b22091e3fc65
编辑状态时，标签字样之前莫名多了一条竖线
而且从正常状态切到编辑状态的时候，标签内的第一个标签，会瞬间闪成黄色又恢复灰色，来不及截图。但是看着还是有点奇怪。
![image](https://cloud.githubusercontent.com/assets/23470504/20331339/b9fca558-abdf-11e6-882f-b1c6ee02e6b4.png)
编辑状态时，封面、封底处的配图应该是那个加号的，不是暂无图片
![image](https://cloud.githubusercontent.com/assets/23470504/20331370/dad8db16-abdf-11e6-8ccb-5907fcaebfa4.png)

**Comment by Alanbuddy** [comment]
@WenJunwen 只剩这一个问题没有修改：从正常状态切到编辑状态的时候，标签内的第一个标签，会瞬间闪成黄色又恢复灰色
