### ISSUE TITLE
管理员后台》儿童中心管理》详情》编辑

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#22]
编辑状态下依然可以操作上架下架
上传完封面照片之后，更改照片，会出现这个状态，照片没有缩放直接100%显示了，还是挺纠结的。
![image](https://cloud.githubusercontent.com/assets/23470504/20332721/dc94b624-abe8-11e6-82e1-d06bee5aaf74.png)

**Comment by Alanbuddy** [comment]
@WenJunwen  已修改
