### ISSUE TITLE
管理员后台》添加儿童中心

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#23]
创建的时候未勾选暂不开放
![image](https://cloud.githubusercontent.com/assets/23470504/20332889/eb797156-abe9-11e6-9ae8-c72017687db8.png)
创建完成后状态依然是未开放
![image](https://cloud.githubusercontent.com/assets/23470504/20332941/3143ce3e-abea-11e6-8311-60034d1bd550.png)

课程等处也是一样，完成直接默认不上架

**Comment by Alanbuddy** [comment]
@WenJunwen 已修改
