### ISSUE TITLE
管理员后台》工作人员管理》详情

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#24]
变成左上角有个返回键的应该比较好吧？这个页只能再次点击工作人员管理返回上页。
![image](https://cloud.githubusercontent.com/assets/23470504/20333209/fecdb2d8-abeb-11e6-8a5c-918d2f64dfd2.png)

**Comment by Alanbuddy** [comment]
@WenJunwen  已修改
