### ISSUE TITLE
管理员后台》课程管理》添加课程

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#25]
在新建页面都有填写的课次和课程编号，完成之后都丢失了。
![image](https://cloud.githubusercontent.com/assets/23470504/20333389/21cd9c2a-abed-11e6-97a5-c36b619933ce.png)
再次编辑的话，课程编号有了，课次还是丢了；然后市场价自己变了（编辑状态还是8000）。
![image](https://cloud.githubusercontent.com/assets/23470504/20333406/4c9c818c-abed-11e6-97b3-b4ea0fe4eb9c.png)
再再次编辑的话，课次和课程编号又丢了，市场价还是变了的（编辑状态还是8000）。
![image](https://cloud.githubusercontent.com/assets/23470504/20333459/a757ce10-abed-11e6-942d-b931e9ff3708.png)

**Comment by JesseYang** [comment]
已修改 @WenJunwen
