### ISSUE TITLE
管理员后台》公告信息管理》新建

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#27]
应该把这个页的样式改成和儿童中心一样的新建公告样式吧？如最后那个
![image](https://cloud.githubusercontent.com/assets/23470504/20333633/d506db5c-abee-11e6-9dc9-e9f538d8d5c3.png)
![image](https://cloud.githubusercontent.com/assets/23470504/20333656/fa4c5482-abee-11e6-8a31-38cf244ed493.png)

**Comment by JesseYang** [comment]
我也发现了，刚才开了另一个issue #26

**Comment by Alanbuddy** [comment]
已修改
