### ISSUE TITLE
儿童中心》课程管理》可开课程》详情

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#32]
在管理员后台的样式如第二张图，在儿童中心的显示如下图所示，图片和……超链接？都以代码的形式显示了。
![image](https://cloud.githubusercontent.com/assets/23470504/20336066/7a39b438-ac02-11e6-899d-80e182183a65.png)
![image](https://cloud.githubusercontent.com/assets/23470504/20336080/8e0a4edc-ac02-11e6-8c3b-f4ab5b021ffe.png)
即使是完全没填课程介绍的页面，也显示有段落和换行代码，挺奇怪的
![image](https://cloud.githubusercontent.com/assets/23470504/20336138/ea805076-ac02-11e6-91ee-5e92789384a9.png)

**Comment by JesseYang** [comment]
已修改 @WenJunwen
