### ISSUE TITLE
儿童中心》儿童管理

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#33]
在本儿童中心添加的学生，在任一儿童中心都能看到了
![image](https://cloud.githubusercontent.com/assets/23470504/20336479/51833570-ac05-11e6-9e39-c7e4d84c2396.png)
![image](https://cloud.githubusercontent.com/assets/23470504/20336482/5bfa38f0-ac05-11e6-861e-353726368f16.png)

**Comment by JesseYang** [comment]
已修改 @WenJunwen
