### ISSUE TITLE
页码

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#36]
左为360浏览器，右为chrome，360这样看着还是挺郁闷的
而且，只有一页的时候，翻页按钮依然可以点，是不是不太好？中间那个框我一直理解成……那种输入数字可以跳转的那种形式，能输是不是好一点？
![image](https://cloud.githubusercontent.com/assets/23470504/20336979/22bc4e8a-ac09-11e6-8745-032a39636e75.png)

**Comment by Alanbuddy** [comment]
@WenJunwen 已修改
