### ISSUE TITLE
儿童中心》绘本管理》添加绘本

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#37]
http://babyplan.bjfpa.org.cn:8000/staff/books/582c0389f6e1d51f7974e226
标签一旦达到五个字，就溢出了
![image](https://cloud.githubusercontent.com/assets/23470504/20337660/58ede58c-ac0d-11e6-842b-4dc426e3b408.png)

**Comment by Alanbuddy** [comment]
@WenJunwen 已修改
