### ISSUE TITLE
管理员后台》绘本管理》详情

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#38]
http://babyplan.bjfpa.org.cn:8000/admin/books/582bebd8f6e1d50f334ddbe3
未上传图片的话，应用“暂无图片”示意图，而不是文字说明
![image](https://cloud.githubusercontent.com/assets/23470504/20337707/afa70048-ac0d-11e6-8173-f860656cb36a.png)

**Comment by Alanbuddy** [comment]
@WenJunwen　已修改

**Comment by Alanbuddy** [comment]
@WenJunwen　已修改
