### ISSUE TITLE
公告信息管理

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#39]
在儿童中心里点击公告的配图时，页面很合理的跳转到了公告的详情页。
但是在管理员后台中，点击公告信息管理中，无论全局公告还是分区公告的配图，页面都跳转到了儿童中心管理页面，跳转错误。
即由
http://babyplan.bjfpa.org.cn:8000/admin/announcements
跳转到了
http://babyplan.bjfpa.org.cn:8000/admin/centers

**Comment by JesseYang** [comment]
已修改 @WenJunwen
