### ISSUE TITLE
儿童中心》儿童管理》详情》课程评价

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#4]
http://babyplan.bjfpa.org.cn/staff/clients/57df534698a9b22091e3fc5b
![image](https://cloud.githubusercontent.com/assets/23470504/20295696/67abe104-ab41-11e6-8c83-02ef12d75adb.png)
这里不应该可选的，建议修改为
![image](https://cloud.githubusercontent.com/assets/23470504/20295889/c0c4680a-ab42-11e6-9909-9ca8591a242c.png)

**Comment by Alanbuddy** [comment]
已修改
