### ISSUE TITLE
表格中的“详情”项

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#42]
把所有表格中的详情去掉，改成点相关的儿童名字、绘本名字、课程名字、儿童中心名字进入详情页
要保留“详情”的只有儿童中心的“迁出记录”“迁入记录”，和管理员后台的“迁移记录”表格
![image](https://cloud.githubusercontent.com/assets/23470504/20338521/8f47fd52-ac12-11e6-85d6-098bcbcdbde8.png)

**Comment by Alanbuddy** [comment]
@WenJunwen 已修改
