### ISSUE TITLE
课程日历   浏览器不兼容问题

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#43]
上为360浏览器，下为chrome浏览器，在360浏览器上两按钮丢失啦
![image](https://cloud.githubusercontent.com/assets/23470504/20339358/d66b847a-ac16-11e6-97a7-341c6679c34b.png)
![image](https://cloud.githubusercontent.com/assets/23470504/20339401/1e181c3e-ac17-11e6-9a3d-b1889ae5f6af.png)

**Comment by Alanbuddy** [comment]
@WenJunwen  已修改
