### ISSUE TITLE
儿童中心》儿童管理》详情》绘本评价

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#5]
http://babyplan.bjfpa.org.cn/staff/clients/57df534698a9b22091e3fc5b
![image](https://cloud.githubusercontent.com/assets/23470504/20296091/cf94f29a-ab43-11e6-93ca-acc9f18ecc6d.png)
附加信息错误，建议改为绘本名称和借阅时间作者……

**Comment by Alanbuddy** [comment]
已修改
