### ISSUE TITLE
工作人员微信端》绘本迁出

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#50]
这个页的下面两个按钮，让它贴底吧
所有类似页面，按钮都放在最底部
![qq 20161117103241](https://cloud.githubusercontent.com/assets/23470504/20374115/4cf6fa4e-acb1-11e6-8049-d31e7a7590bb.png)

**Comment by Alanbuddy** [comment]
@WenJunwen  已修改
