### ISSUE TITLE
儿童中心

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#6]
![image](https://cloud.githubusercontent.com/assets/23470504/20296170/3c932c04-ab44-11e6-8017-0a9c21834381.png)
无相关跳转 建议改为
![image](https://cloud.githubusercontent.com/assets/23470504/20297034/3e453786-ab49-11e6-954e-109c3d718bda.png)

**Comment by Alanbuddy** [comment]
已修改
