### ISSUE TITLE
儿童中心》课程管理》新建课程

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#68]
1、这门课开起来了……负数也可以
![image](https://cloud.githubusercontent.com/assets/23470504/20416397/b134958e-ad79-11e6-98bb-dc8d0d01b332.png)
2、回退之后，再进来，容量就变成4了
![image](https://cloud.githubusercontent.com/assets/23470504/20416642/2c163e00-ad7b-11e6-95f5-8afc04bb81de.png)
3、这门课程是下架状态，但是在用户微信端依然可以查询到

**Comment by JesseYang** [comment]
均已修改
