### ISSUE TITLE
管理员后台》绘本管理》绘本迁移

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#73]
http://babyplan.bjfpa.org.cn/admin/transfers/582d1647f6e1d51ab7711a49
迁移的详情一点进去就报错
![image](https://cloud.githubusercontent.com/assets/23470504/20420110/2c17672e-ad96-11e6-84c5-996e389bb984.png)

**Comment by JesseYang** [comment]
已修改
