### ISSUE TITLE
儿童中心》课程管理》详情》编辑

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#87]
金额倒还好，但人数、课次可以设小数好像就比较奇怪了
另，课程开设之后，别的都能成功修改，但容量（是不是直接用最大人数比较好？我觉得这个有点难理解），修改之后，退出再返回，还是之前的那个人数
![image](https://cloud.githubusercontent.com/assets/23470504/20468114/ec92d8f6-afcd-11e6-99d2-d0abe2810a84.png)

**Comment by JesseYang** [comment]
已修改。容量可以正常编辑；容量和课次都强制转成了整数
