### ISSUE TITLE
儿童中心》课程管理》详情》修改

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#89]
课程编号在修改时，可修改为完全一样
![image](https://cloud.githubusercontent.com/assets/23470504/20468834/ac13ded0-afd5-11e6-914f-8137ff6eebb8.png)
![image](https://cloud.githubusercontent.com/assets/23470504/20468838/b4a97ea6-afd5-11e6-80ff-5ab3644390ab.png)

**Comment by JesseYang** [comment]
已修改
