### ISSUE TITLE
儿童中心》绘本管理》绘本详情》编辑

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#9]
http://babyplan.bjfpa.org.cn/staff/books/57df540798a9b22091e3fc5d
编辑状态应如课程管理处有类似处理，编辑时在图片上再蒙一层添加标记。
![image](https://cloud.githubusercontent.com/assets/23470504/20298072/ec1685e0-ab4e-11e6-8322-32f122cd13a4.png)
![image](https://cloud.githubusercontent.com/assets/23470504/20298112/18274dc2-ab4f-11e6-942d-31a2bdc88963.png)

**Comment by Alanbuddy** [comment]
@WenJunwen 已修改
