### ISSUE TITLE
管理员后台》儿童中心管理》添加

### ISSUE THREAD

**Issue by WenJunwen** [BuddyRobots/BabyPlan#95]
在中心名称、详细地址处不管输入文字与否，只要一回车，页面就全刷新没有了
课程管理页面没有该现象
公告信息管理页，公告标题处回车同样现象

儿童中心，课程管理》可开课程》开设课程，上课时间和地址处一回车，页面就跳转到了课程管理》本区开课处。
绘本管理处正常
公告管理处一样有问题。

**Comment by JesseYang** [comment]
页面中用了很多form，导致回车会提交表单 @Alanbuddy

**Comment by Alanbuddy** [comment]
@WenJunwen 已修改
